# Generated by Django 2.2.7 on 2019-12-09 21:25

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0141_seat_sorting_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('target', models.EmailField(max_length=254)),
                ('user_comment', models.TextField()),
                ('authorized', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Order')),
                ('vouchers', models.ManyToManyField(to='pretixbase.Voucher')),
            ],
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='LotteryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=200)),
                ('cookie', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event')),
                ('vouchers', models.ManyToManyField(to='pretixbase.Voucher')),
            ],
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.UniqueConstraint(condition=models.Q(status='p'), fields=('order',), name='only_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='lotteryentry',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='register_email_once'),
        ),
        migrations.AddConstraint(
            model_name='lotteryentry',
            constraint=models.UniqueConstraint(fields=('event', 'first_name', 'last_name', 'dob'), name='register_person_once'),
        ),
    ]
