# Generated by Django 2.2.7 on 2019-12-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_borderland', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lotteryentry',
            name='register_person_once',
        ),
        migrations.AlterField(
            model_name='lotteryentry',
            name='browser',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='lotteryentry',
            name='cookie',
            field=models.CharField(max_length=2048),
        ),
    ]
